package in.codegram.doctorpatient.modal;

/**
 * This Patient Modal is used to hold the data and will travel layer to layer.
 * @author ranjeet
 *
 */
public class Patient {
	
	/**
	 * id of the patient
	 * AutoGenerated
	 */
	private Integer id;
	/**
	 * name of the patient. PatientName is required
	 */
	private String patientName;
	/**
	 * speciality of the doctor. speciality is required
	 */
	private String problem;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getPatientName() {
		return patientName;
	}
	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}
	public String getProblem() {
		return problem;
	}
	public void setProblem(String problem) {
		this.problem = problem;
	}
	@Override
	public String toString() {
		return "Patient [id=" + id + ", patientName=" + patientName + ", problem=" + problem + "]";
	}
}
