package in.codegram.calender_module.util;

public enum Status {
	LOGIN_SUCCESS,
	LOGOUT_SUCCESS,
	USERNAME_AND_PASSWORD_NOT_CORRECT,
	USERNAME_NOT_CORRECT,
	PASSWORD_NOT_CORRECT,
	USERNAME_NOT_FOUND,
	PASSWORD_UPDATED_SUCCESSFULLY,
	PROFILE_UPDATION_FAILED

}
