package in.codegram.trainingtracker.modal;

import java.util.Date;

/**
 * This Porject Modal is used to hold the data and will travel layer to layer
 * @author ranjeet
 *
 */

public class Employee {
	
	/**
	 * id of the employee
	 * AutoGenerated
	 */
	private Integer id;
	/**
	 * name of the employee. EmployeeName is required
	 */
	private String employeeName;
	/**
	 * type of employee. EmployeeTyep is required
	 */
	private String employeeType;
	/**
	 * employee department of the employee
	 */
	private String employeeDepartment;
	/**
	 * date at which employee get enrolled
	 */
	private Date createdAt;
	/**
	 * date at which employee data updated
	 */
	private Date updatedAt;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public String getEmployeeType() {
		return employeeType;
	}
	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}
	public String getEmployeeDepartment() {
		return employeeDepartment;
	}
	public void setEmployeeDepartment(String employeeDepartment) {
		this.employeeDepartment = employeeDepartment;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	@Override
	public String toString() {
		return "Employee [id=" + id + ", employeeName=" + employeeName + ", employeeType=" + employeeType
				+ ", employeeDepartment=" + employeeDepartment + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt
				+ "]";
	}
}
