package in.codegram.kanbantool.modal;

import java.util.Date;

/**
 * This Project Modal is used to hold the data and will travel layer to layer.
 * @author ranjeet
 *
 */
public class Project {
	
	/**
	 * id of the project
	 * AutoGenerated
	 */
	private Integer id;
	/**
	 * name of the project. ProjectName is required
	 */
	private String projectName;
	/**
	 * identifier of the project. it should be unique
	 */
	private String projectIdentifier;
	/**
	 * description of the project required
	 */
	private String description;
	/**
	 * start date of the project
	 */
	private Date startDate;
	/**
	 * end date of the project
	 */
	private Date endDate;
	/**
	 * date at which project is created
	 */
	private Date createdAt;
	/**
	 * date at which project is updated
	 */
	private Date updatedAt;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	public String getProjectIdentifier() {
		return projectIdentifier;
	}
	public void setProjectIdentifier(String projectIdentifier) {
		this.projectIdentifier = projectIdentifier;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	@Override
	public String toString() {
		return "Project [id=" + id + ", projectName=" + projectName + ", projectIdentifier=" + projectIdentifier
				+ ", description=" + description + ", startDate=" + startDate + ", endDate=" + endDate + ", createdAt="
				+ createdAt + ", updatedAt=" + updatedAt + "]";
	}
}
