package in.codegram.doctorpatient.modal;

/**
 * This Doctor Modal is used to hold the data and will travel layer to layer.
 * @author ranjeet
 *
 */
public class Doctor {
	
	/**
	 * id of the doctor
	 * AutoGenerated
	 */
	private Integer id;
	/**
	 * name of the doctor. DoctorName is required
	 */
	private String doctorName;
	/**
	 * speciality of the doctor. speciality is required
	 */
	private String speciality;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDoctorName() {
		return doctorName;
	}
	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}
	public String getSpeciality() {
		return speciality;
	}
	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}
	@Override
	public String toString() {
		return "Doctor [id=" + id + ", doctorName=" + doctorName + ", speciality=" + speciality + "]";
	}
}
